site_name: HackWeek Toolkit
nav:
    - Home: index.md
    - Venues:
        - 'Introduction': 'Venues/Venues-General.md'
        - 'Examples': 'Venues/Venues-Ideas.md'
    - Facilitation:
        - 'Introduction': 'Facilitation/Facilitation-intro.md'
        - 'Opening': 'Facilitation/opening.md'
        - 'Project Formation': 'Facilitation/projects.md'
    - Hacking: 
        - 'Introduction': 'Hacking/Hacking-intro.md'
    - Participant Selection: 
        - 'Introduction': 'ParticipantSelection/ParticipantSelection-intro.md'
    - Tutorials: 
        - 'Introduction': 'Tutorials/Tutorials-intro.md'
    - Website: Website.md
theme: 
    name: readthedocs
    highlightjs: true
plugins:
    - search
markdown_extensions:
  - admonition
repo_url: https://github.com/uwescience/HackWeek-Toolkit