site_name: HackWeek Toolkit
nav:
    - Home: index.md
    - About: about.md
    - Organizing Committee:
        - 'Introduction': 'OrganizingCommittee/Committee-intro.md'
        - 'Formation': 'OrganizingCommittee/Committee-formation.md'
        - 'Structure': 'OrganizingCommittee/Committee-structure.md'
    - Venues:
        - 'Introduction': 'Venues/Venues-General.md'
        - 'Examples': 'Venues/Venues-Ideas.md'
    - Participant Selection: 
        - 'Introduction': 'ParticipantSelection/ParticipantSelection-intro.md'
    - Facilitation:
        - 'Introduction': 'Facilitation/Facilitation-intro.md'
        - 'Opening the Event': 'Facilitation/event-introduction.md'
        - 'Setting the Stage': 'Facilitation/community-building.md'
        - 'Pitching Hacks/Projects': 'Facilitation/pitching-hacks.md'
        - 'Checking In': 'Facilitation/checking-in.md'
        - 'Mediating Conflict': 'Facilitation/mediating-conflict.md'
        - 'Wrapping Up': 'Facilitation/wrap-up.md'
        - 'Astrohackweek Facilitation': 'Facilitation/AHW-Facilitation.md'
        - 'Geohackweek Facilitation': 'Facilitation/GHW-facilitation.md'
        - 'Future Experiments': 'Facilitation/Future-experiments.md'
    - Hacking: 
        - 'Introduction': 'Hacking/Hacks-Intro.md'
        - 'Astro Hack Week Template': 'Hacking/AHW-Hack-Template.md'
    - Tutorials: 
        - 'Introduction': 'Tutorials/Tutorials-intro.md'
        - 'Design': 'Tutorials/Tutorial-design.md'
    - Website: 
        - 'Website': 'Website/Website-intro.md'
theme: 
    name: readthedocs
    highlightjs: true
plugins:
    - search
markdown_extensions:
  - admonition
repo_url: https://github.com/uwescience/HackWeek-Toolkit